#+TITLE: Web del repositorio
#+SUBTITLE: Notas para recordar cómo lo hice.

La web del repositorio esta en esta dirección: [[https://mbujosab.github.io/temporizador-examen/]]

Lo que sigue es un recordatorio de los pasos necesarios para crearla

* Publicación                                                      :noexport:

El siguiente =makefile= genera algunos subdirectorios y hace tangle del código =html= correspondiente a los temporizadores desde el fichero fuente [[file:examtimer.org][=examtimer.org=]].

#+BEGIN_SRC makefile :noweb no-export :results silent :tangle makefile  :eval no
publica: temporizadores README.org index.org examtimer.org
	emacs --batch -l publica.el
	touch $@

temporizadores: 
	emacs -q --batch examtimer.org -l org -f org-babel-tangle

directorios:
	mkdir -v -p .github/workflows
	mkdir -v -p docs/temporizadores
	cp -a ./css docs/
	touch directorios

clean:
	rm -r -f docs
	rm -f directorios
	rm -f publica

#+END_SRC

El siguiente script de elisp publica el fichero [[file:index.org][=index.org=]] en formato  =html= en el subdirectorio =./docs=. El objetivo =publica= del script =makefile= indica a =emacs= que ejecute este código de elisp mediante el siguiente comando: =emacs --batch -l publica.el=


#+BEGIN_SRC emacs-lisp :tangle publica.el :results silent :eval no
(require 'org)
(require 'ox-html)

(setq org-publish-project-alist
      '(("index"
         :base-directory "./"
         :base-extension "org"
         :publishing-directory "./docs/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 1 ;; Just for this example
         :auto-preamble t
         :auto-sitemap nil
         :with-author t
         :with-creator nil
         :with-toc t
	 :exclude "README.org\\|examtimer.org"
	 :section-numbers nil)
	))

(org-publish-project "index")
#+END_SRC


** Pasos para crear la rama =gh-pages=, configurar GitHub Pages y crear el archivo =build.yml=.

Esto hace las veces de un tutorial para publicación de un repositorio en GitHub en una rama específica para la publicación de ciertos ficheros generados con Actions en GutHub al hacer push de un nuevo commit.

*** Pasos para crear la rama =gh-pages=

1. *Crea la rama =gh-pages=*:
2. en Settings -> Pages
   - indicar que la rama de publicación es =gh-pages= 
   - el directorio =/docs=
   Y salvar esta configuración
2. en Settings -> Secrets and Variables -> Actions
   - en =Repository secrets= añadir un secreto previamente creado. El nombre iondicado debe ser el mismo que se indica al final de =.github/workflows/build.yml=

*** Contenido del archivo =.github/workflows/build.yml=

#+BEGIN_SRC emacs-lisp :exports none :results silent :tangle no :eval yes
(unless (file-directory-p ".github")
  (make-directory ".github"))
(unless (file-directory-p ".github/workflows")
  (make-directory ".github/workflows"))
#+END_SRC


A continuación, el contenido sugerido para =build.yml=:

#+begin_src yaml :tangle .github/workflows/build.yml
name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio principal
        uses: actions/checkout@v4

      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs

      - name: Tangle Publicacion_del_repositorio.org
        run: emacs --batch Publicacion_del_repositorio.org -l org -f org-babel-tangle

      - name: Run Makefile
        run: make publica

      - name: Deploy docs/ a gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.NUEVO_TOKEN_CLASSIC_HASTA_JULIO_2026 }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
          allow_empty_commit: true

#+end_src

*** Notas adicionales:

- *Verificar que el repositorio tiene un README.org y el makefile correctamente configurado.*
- *Verificar que existe el directorio =.github/workflows/=; y que en el está el fichero =build.yml=.*

Con estos pasos, al hacer un push a la rama =main=, se ejecutará este flujo de trabajo, se generarán los archivos y se desplegarán automáticamente en GitHub Pages.
